services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
        PORT: 3000
        DATABASE_URL: mongodb://mongo:27017/todo-list
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: